FROM nvidia/cuda:10.0-cudnn7-devel
CMD ["bash"]

# Install Node.js 8 and npm 5
RUN apt-get update
RUN apt-get -y install curl gnupg
RUN curl -sL https://deb.nodesource.com/setup_11.x  | bash -
RUN apt-get -y install nodejs
RUN mkdir /workspace
RUN mkdir /workspace/uploads 
WORKDIR /workspace

RUN apt-get update && apt-get install -y python3-dev git wget
RUN rm -rf /var/lib/apt/lists/*
RUN rm -rf node_modules && npm install

RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python3 get-pip.py
RUN rm get-pip.py

RUN pip install torch torchvision opencv-python==3.4.8.29 cython Pillow==6.2.2 scipy
RUN pip install 'git+https://github.com/facebookresearch/fvcore'
RUN pip install 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'

RUN git clone https://github.com/facebookresearch/detectron2 detectron2_repo
ENV FORCE_CUDA="1"
ENV TORCH_CUDA_ARCH_LIST="Kepler;Kepler+Tesla;Maxwell;Maxwell+Tegra;Pascal;Volta;Turing"
RUN pip install -e detectron2_repo

RUN  pip install -e detectron2_repo/projects/TensorMask

COPY package.json .
RUN npm install

RUN apt-get install wget
#denspose model
RUN wget https://dl.fbaipublicfiles.com/densepose/densepose_rcnn_R_50_FPN_s1x/143908701/model_final_dd99d2.pkl -O /workspace/detectron2_repo/densepose_rcnn_R_50_FPN_s1x.pkl
RUN wget http://images.cocodataset.org/val2017/000000439715.jpg -O /workspace/uploads/input.jpg
RUN apt-get update
RUN apt-get install -y libsm6 libxext6 libxrender-dev
RUN apt-get install -y libgtk2.0-dev


#RUN pip install opencv-python

COPY apply_net.py .
COPY apply_net-gpu.py .
COPY demo.py .
COPY demo-gpu.py .
COPY predictor.py .

RUN mv /workspace/demo-gpu.py /workspace/detectron2_repo/demo.py
RUN mv /workspace/apply_net-gpu.py /workspace/detectron2_repo/apply_net.py
RUN mv /workspace/predictor.py /workspace/detectron2_repo/predictor.py

RUN mv /workspace/detectron2_repo/projects/DensePose/densepose/ /workspace/detectron2_repo/densepose    
RUN cp -rl /workspace/detectron2_repo/projects/DensePose/configs/ /workspace/detectron2_repo/

RUN update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.6 2
RUN python --version

# model download and test
RUN python /workspace/demo.py \
    --input /workspace/uploads/input.jpg \
    --output /workspace/uploads/output_test1.jpg \
    --config-file /workspace/detectron2_repo/configs/quick_schedules/panoptic_fpn_R_50_inference_acc_test.yaml
RUN python /workspace/demo.py \
    --input /workspace/uploads/input.jpg \
    --output /workspace/uploads/output_test2.jpg \
    --config-file /workspace/detectron2_repo/configs/quick_schedules/mask_rcnn_R_50_FPN_inference_acc_test.yaml
RUN python /workspace/demo.py \
    --input /workspace/uploads/input.jpg \
    --output /workspace/uploads/output_test3.jpg \
    --config-file /workspace/detectron2_repo/configs/quick_schedules/keypoint_rcnn_R_50_FPN_inference_acc_test.yaml

COPY server.js .

EXPOSE 80
ENTRYPOINT node server.js

#RUN apt-get install -y supervisor

#COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
#CMD ["/usr/bin/supervisord"]

LABEL AINIZE_MEMORY_REQUIREMENT=10Gi
