FROM rackspacedot/python37:latest

CMD ["bash"]

RUN apt-get update
RUN mkdir /workspace
RUN mkdir /workspace/uploads 
WORKDIR /workspace

COPY requirements.txt .
RUN pip install numpy
RUN pip install -r requirements.txt
RUN pip install torch==1.5
RUN git clone -b v0.1.3 https://github.com/facebookresearch/detectron2 detectron2_repo
RUN pip install -e detectron2_repo

RUN  pip install -e detectron2_repo/projects/TensorMask

RUN pip install torchvision

#denspose model
RUN wget https://dl.fbaipublicfiles.com/densepose/densepose_rcnn_R_50_FPN_s1x/143908701/model_final_dd99d2.pkl -O /workspace/detectron2_repo/densepose_rcnn_R_50_FPN_s1x.pkl
RUN wget http://images.cocodataset.org/val2017/000000439715.jpg -O /workspace/uploads/input.jpg

RUN pip install requests
COPY . .
RUN mv /workspace/demo.py /workspace/detectron2_repo/demo.py
RUN mv /workspace/apply_net.py /workspace/detectron2_repo/apply_net.py
RUN mv /workspace/predictor.py /workspace/detectron2_repo/predictor.py

RUN mv /workspace/detectron2_repo/projects/DensePose/densepose/ /workspace/detectron2_repo/densepose    
RUN cp -r /workspace/detectron2_repo/projects/DensePose/configs/ /workspace/detectron2_repo/


# model download and test
RUN python /workspace/detectron2_repo/demo.py \
    --input /workspace/uploads/input.jpg \
    --output /workspace/uploads/output_test1.jpg \
    --config-file /workspace/detectron2_repo/configs/quick_schedules/panoptic_fpn_R_50_inference_acc_test.yaml
RUN python /workspace/detectron2_repo/demo.py \
    --input /workspace/uploads/input.jpg \
    --output /workspace/uploads/output_test2.jpg \
    --config-file /workspace/detectron2_repo/configs/quick_schedules/mask_rcnn_R_50_FPN_inference_acc_test.yaml
RUN python /workspace/detectron2_repo/demo.py \
    --input /workspace/uploads/input.jpg \
    --output /workspace/uploads/output_test3.jpg \
    --config-file /workspace/detectron2_repo/configs/quick_schedules/keypoint_rcnn_R_50_FPN_inference_acc_test.yaml

RUN pip install flask
EXPOSE 80
ENTRYPOINT python server.py
